from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint

from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

# these 3 will segregaate out prompts into 3 categories 
# 1. System message always at the start of the model it explain the model how it should act like act as a helpful assistant 
# 2. HumanMessage this is our input 
# 3. AIMessage this is the one generated by ai 
# now we can store all these 3 types of messages into a Chat_History list and send it to our model for context 

load_dotenv()

# model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7 )

llm = HuggingFaceEndpoint(
    repo_id="Qwen/Qwen2.5-7B-Instruct",
    task="conversational",
    max_new_tokens=400,
    temperature=0.7,
)
model = ChatHuggingFace(llm=llm)

# while True:
#     user_input = input("Priyanshu : ")
#     if user_input == "End":
#         break
#     result = model.invoke(user_input)
#     print("Friday: ",result.content)

# till this point the model doesnt have any context about out chat history so now we are going to apply that here.


Chat_History = [
    SystemMessage(content="You are a Mathamatician")
] 


while True:
    user_input = input("Priyanshu: ")
    Chat_History.append(HumanMessage(content=user_input))
    if user_input == "end":
        break
    result = model.invoke(Chat_History)
    # here we sent the whole chat history into the model
    Chat_History.append(result)
    print("AI: ",result.content)

print(Chat_History.content)


# now in this implementation our model have context about our Chat_History

